local PetData = {

    Egg1 = {

        { name = "Dog", rarity = "common", chance = 30 },
        { name = "Cat", rarity = "common", chance = 30 },
        { name = "Rabbit", rarity = "common", chance = 30 },
        { name = "Deer", rarity = "uncommon", chance = 10 }

    },

    Egg2 = {

        { name = "Tiger", rarity = "common", chance = 30 },
        { name = "Gold Fish", rarity = "rare", chance = 20 },
        { name = "Elephant", rarity = "epic", chance = 10 },
        { name = "Lion", rarity = "legendary", chance = 5 }

    },

    Egg3 = {

        { name = "Rat", rarity = "common", chance = 40 },
        { name = "Mouse", rarity = "rare", chance = 20 },
        { name = "Scorpion", rarity = "epic", chance = 10 },
        { name = "Panther", rarity = "legendary", chance = 1 }

    }

}
return PetData